#!/usr/bin/env bash
#
# Experiment 09 (libsodium, CIO parity) on Apple silicon, from a clean machine.
#
#   git clone <this repo> && cd <it>
#   utils/taint_libsodium_silicon_reproduce.sh
#
# One command: toolchain, libsodium source, CIO's drivers, the five library
# arms, the run, the report. Every stage is skipped if its output already
# exists, so re-running is cheap and a failed run resumes where it stopped.
#
# This is the Apple-silicon counterpart of
# utils/dit_host_screening/cioparity/reproduce.sh, which does the same for gem5.
# The arms are built at the SAME compiler configuration as that rig
# (utils/taint_libsodium_arms.sh); the point of running both is that the machine
# is the only thing that differs.
#
# WHAT IT MEASURES. Four arms and their layout controls, per CIO benchmark:
# unhardened, blanket DIT, Apple's API bracket (`sb`), and ExpeDITe at the
# shipped defaults. See taint_libsodium_sudo_run.sh for the arm table.
#
# WORKS ON M4 AND M5, and on anything else with FEAT_DIT. Nothing here is tuned
# to a part: the P-core residency gate tests > 4000 MHz rather than a specific
# clock, and the DIT-visibility gate tests cycles per hop (predicted ~1 with DIT
# off, L1 load-to-use with it on) rather than a ratio, because that ratio's
# ceiling IS the L1 latency -- 4 on M5, 3 on M4 -- and a fixed threshold is
# unsatisfiable on the shorter one.
#
# STAGES   toolchain source cio arms counters run report
#
# ENV
#   LLVM_BIN=<dir>    prebuilt taint toolchain; skips the toolchain stage
#   BUILD=<dir>       where to build it        (default <repo>/build)
#   ROOT=<dir>        parent for work dirs     (default ~/Documents)
#   CIO_REPS=<n>      reps per benchmark       (default 15, the paper's protocol)
#   SKIP_ARGON=1      drop argon2id: ~60 of the run's ~70 minutes, and the row
#                     least likely to resolve (it is free in every arm)
#   NO_SUDO=1         force the unrooted path even without PMC. Ratios stay
#                     valid -- the parity preset times with CNTVCT either way --
#                     but you lose the cycle and instruction columns entirely.
#
# COUNTERS ARE CHOSEN BY TESTING, not by you. The `counters` stage runs
# utils/cio_pmc_check.c: if this kernel exposes Apple's PMCs to EL0
# (PMCR0_USEREN_EN, via github.com/jprx/PacmanPatcher) the run uses them --
# exact counts, ~39 cycles per ordered read, and NO SUDO PROMPT AT ALL, since
# root was only ever needed for kperf. Otherwise it falls back to kperf and asks
# for sudo, and you should remember that path's ~3,400-cycle per-region offset
# before quoting an absolute IPC off it.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="${ROOT:-$HOME/Documents}"
BUILD="${BUILD:-$REPO_ROOT/build}"
SODIUM_VER="${SODIUM_VER:-1.0.21}"
SRC="${SRC:-$ROOT/libsodium-$SODIUM_VER}"
ARMS_WORK="${ARMS_WORK:-$ROOT/libsodium-arms-silicon}"
CIO_DIR="${CIO_DIR:-$ROOT/cio-eval}"
BENCH_DIR="${BENCH_DIR:-$ROOT/crypto-dit-benchmarks}"
OUT="${OUT:-$ROOT/dit-silicon-parity-$(date +%Y%m%d-%H%M%S)}"
CIO_REPS="${CIO_REPS:-15}"
JOBS="${JOBS:-$(sysctl -n hw.ncpu 2>/dev/null || echo 8)}"

# The runner needs libsodium's headers, and sodium/version.h is GENERATED by
# configure (configure.ac AC_CONFIG_FILES). A freshly unpacked tarball does not
# have it, so pointing the runner at the pristine source tree fails on a clean
# machine and works on one where some earlier script happened to configure it.
# Point it at the base variant's build tree instead, which is always configured.
LIBWORK="$ARMS_WORK/base"

info() { printf '\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m    %s\033[0m\n' "$*"; }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

ALL_STAGES="toolchain source cio arms counters run report"
[[ "${1:-}" == "--list" ]] && { echo "$ALL_STAGES"; exit 0; }
STAGES="${*:-$ALL_STAGES}"
want() { [[ " $STAGES " == *" $1 "* ]]; }

# ---------------------------------------------------------------- preflight
[[ "$(uname -s)" == Darwin ]] || die "this is the Apple-silicon rig; for gem5 use utils/dit_host_screening/cioparity/reproduce.sh"
[[ "$(uname -m)" == arm64 ]]  || die "not arm64"
[[ "$(sysctl -n hw.optional.arm.FEAT_DIT 2>/dev/null)" == 1 ]] \
  || die "this CPU has no FEAT_DIT -- PSTATE.DIT cannot be set, so no arm here means anything"
command -v xcrun >/dev/null || die "Xcode command line tools missing: xcode-select --install"
info "host: $(sysctl -n hw.model) / $(sysctl -n machdep.cpu.brand_string), FEAT_DIT present"

# ---------------------------------------------------------------- toolchain
# The shipped defaults (callee contract, twins, owned list) exist only in a
# toolchain built after 2026-09-05. An older clang ACCEPTS -ftaint-harden and
# ignores the flags it does not know, so it would build the pre-contract arm
# under the name `taint`: a wrong number that looks like a right one.
has_new_pass() { [[ -x "${1:-}/llc" ]] && "$1/llc" --help-hidden 2>/dev/null | grep -q -- '-taint-owned-symbols'; }

# Look for a usable toolchain before deciding to build one. A checkout without
# its own build/ is the normal case -- a git worktree, a fresh clone, a second
# tree for a branch -- and the toolchain is not per-checkout: any build of this
# branch compiles the same arms. Spending two hours because the caller cd'd into
# the wrong tree is a bad trade, and it is what this script used to do.
toolchain_candidates() {
  [[ -n "${LLVM_BIN:-}" ]] && echo "$LLVM_BIN"
  echo "$BUILD/bin"
  echo "$REPO_ROOT/build/bin"
  # sibling checkouts and worktrees of this repo, including the one a worktree
  # was created from; then anything already on PATH.
  local base; base="$(basename "$REPO_ROOT")"
  for d in "$HOME/Documents/$base" "$HOME/$base" "$REPO_ROOT"/../*/"$base"; do
    [[ -d "$d" ]] && echo "$d/build/bin"
  done
  command -v llc >/dev/null && dirname "$(command -v llc)"
}

FOUND=""
while read -r cand; do
  [[ -n "$cand" ]] || continue
  if has_new_pass "$cand"; then FOUND="$cand"; break; fi
done < <(toolchain_candidates)

build_from_scratch() {
  warn "BUILD_TOOLCHAIN=1: configuring $BUILD from scratch. Expect a couple of hours."
  command -v cmake >/dev/null || die "cmake not found (brew install cmake ninja)"
  command -v ninja >/dev/null || die "ninja not found (brew install ninja)"
  [[ -f "$REPO_ROOT/llvm/CMakeLists.txt" ]] \
    || die "no llvm/ in $REPO_ROOT -- is this the right checkout?"
  cmake -G Ninja -S "$REPO_ROOT/llvm" -B "$BUILD" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS='clang;lld' \
    -DLLVM_TARGETS_TO_BUILD='AArch64;X86' \
    -DLLVM_ENABLE_ASSERTIONS=OFF > "$BUILD.cmake.log" 2>&1 \
    || { tail -20 "$BUILD.cmake.log" >&2; die "cmake configure failed"; }
  ninja -C "$BUILD" clang llc opt llvm-nm llvm-ar llvm-objdump llvm-link llvm-dis \
    || die "toolchain build failed"
  LLVM_BIN="$BUILD/bin"
  has_new_pass "$LLVM_BIN" || die "built toolchain still lacks -taint-owned-symbols -- wrong branch?"
}

# BUILD_TOOLCHAIN must be handled INSIDE this chain. It used to sit in a second
# `if` after it, which the no-toolchain branch could never reach: that branch
# calls die(), so the flag the error message told you to set did nothing at all.
if [[ -n "$FOUND" ]]; then
  [[ -n "${LLVM_BIN:-}" && "$FOUND" != "$LLVM_BIN" ]] && warn "LLVM_BIN had no usable pass; using $FOUND"
  LLVM_BIN="$FOUND"
  info "toolchain: $LLVM_BIN"
elif [[ -n "${LLVM_BIN:-}" ]]; then
  die "LLVM_BIN=$LLVM_BIN has no -taint-owned-symbols (pre-2026-09-05 compiler)"
elif ! want toolchain; then
  die "no usable toolchain and the 'toolchain' stage was not requested"
elif [[ -f "$BUILD/CMakeCache.txt" ]]; then
  # An existing build dir means an incremental build: minutes, not hours.
  info "toolchain: rebuilding $BUILD incrementally"
  ninja -C "$BUILD" clang llc opt llvm-nm llvm-ar llvm-objdump llvm-link llvm-dis \
    || die "toolchain build failed"
  LLVM_BIN="$BUILD/bin"
  has_new_pass "$LLVM_BIN" || die "built toolchain still lacks -taint-owned-symbols -- wrong branch?"
elif [[ "${BUILD_TOOLCHAIN:-0}" == 1 ]]; then
  build_from_scratch
else
  # A build FROM SCRATCH is hours, so it never starts implicitly. It is almost
  # always the wrong answer: the usual cause is running from a checkout that has
  # no build/ while a perfectly good toolchain sits in another one.
  die "no usable toolchain found. Searched:
$(toolchain_candidates | awk '!seen[$0]++' | sed 's/^/       /')

     If you have one, point at it:
       LLVM_BIN=<dir>/build/bin $0

     To build one here from scratch (hours):
       BUILD_TOOLCHAIN=1 $0"
fi
export LLVM_BIN

# ---------------------------------------------------------------- source
if want source && [[ ! -d "$SRC" ]]; then
  info "fetch libsodium $SODIUM_VER"
  mkdir -p "$ROOT"
  ( cd "$ROOT" \
    && curl -sSL --max-time 300 -o "libsodium-$SODIUM_VER.tar.gz" \
         "https://download.libsodium.org/libsodium/releases/libsodium-$SODIUM_VER.tar.gz" \
    && tar xzf "libsodium-$SODIUM_VER.tar.gz" ) || die "libsodium download failed"
  [[ -d "$SRC" ]] || die "tarball did not unpack to $SRC"
fi
[[ -d "$SRC" ]] || die "no libsodium source at $SRC"

# ---------------------------------------------------------------- cio
# CIO's six drivers plus our eval_util.h port. Self-contained: it curls from
# GitHub when there is no local CIO clone.
if want cio && [[ ! -f "$CIO_DIR/eval_util.h" ]]; then
  info "stage CIO's drivers -> $CIO_DIR"
  CIO_DIR="$CIO_DIR" bash "$REPO_ROOT/utils/taint_cio_eval_setup.sh" \
    || die "CIO driver staging failed"
fi
[[ -f "$CIO_DIR/eval_util.h" ]] || die "no CIO drivers at $CIO_DIR"

# ---------------------------------------------------------------- arms
if want arms; then
  info "build the library arms (gem5-parity compiler configuration)"
  SRC="$SRC" ARMS_WORK="$ARMS_WORK" WORK="$LIBWORK" JOBS="$JOBS" \
    bash "$REPO_ROOT/utils/taint_libsodium_arms.sh" || die "arm build failed"
fi

# ---------------------------------------------------------------- counters
# Pick the counter source by testing for it, rather than making the caller know
# which kind of machine they are on.
#
#   PMC     Apple's fixed counters read straight from EL0, one `mrs`. Needs a
#           kernel patched with PMCR0_USEREN_EN (github.com/jprx/PacmanPatcher).
#           Costs 1 cycle bare, ~39 isb-ordered, against kperf's ~3,400 -- and
#           needs NO ROOT, so it skips the sudo prompt entirely.
#   kperf   the fallback everywhere else. Needs root, and carries a ~3,400-cycle
#           / ~17,700-instruction offset per region that has to be corrected for
#           before absolute IPC means anything.
#
# utils/cio_pmc_check.c is the gate and exits non-zero for each way this can go
# wrong: registers trap, registers read but do not count, or nops do not retire
# (which would make every NOP layout control unsound). Run it standalone any
# time with:  clang -O1 -o /tmp/pmc_check utils/cio_pmc_check.c && /tmp/pmc_check
PMC=0
if want run || want counters; then
  info "counter source"
  PMC_BIN="${TMPDIR:-/tmp}/cio_pmc_check.$$"
  if clang -O1 -o "$PMC_BIN" "$REPO_ROOT/utils/cio_pmc_check.c" 2>/dev/null \
     && "$PMC_BIN" 2>&1 | sed 's/^/    /'; then
    PMC=1
    info "    -> PMC available: exact counters, no root needed"
  else
    warn "-> PMC unavailable; using kperf (root) and its ~3400-cycle region offset"
    warn "   enable with github.com/jprx/PacmanPatcher to drop the correction"
  fi
  rm -f "$PMC_BIN"
fi

# ---------------------------------------------------------------- run
if want run; then
  # A caller's CIOB wins, so a single benchmark can be re-run without editing.
  if [[ -z "${CIOB:-}" ]]; then
    CIOB="ed25519 chacha20_poly1305_encrypt chacha20_poly1305_decrypt aesni256gcm_encrypt aesni256gcm_decrypt"
    [[ "${SKIP_ARGON:-0}" == 1 ]] || CIOB="$CIOB argon2id"
  fi
  info "run: $CIO_REPS reps, $(echo $CIOB | wc -w | tr -d ' ') benchmarks -> $OUT"
  [[ "${SKIP_ARGON:-0}" == 1 ]] && warn "SKIP_ARGON=1: argon2id omitted"

  # OURS=ditprobe keeps PART 1 to the gate instrument alone. The 13-primitive
  # rig is a different experiment and is not part of 09.
  env_args=(LLVM_BIN="$LLVM_BIN" WORK="$LIBWORK" CIO_DIR="$CIO_DIR"
            BENCH_DIR="$BENCH_DIR" OUT="$OUT" CIO_REPS="$CIO_REPS" REPS=5
            OURS=ditprobe CIOB="$CIOB" PMC="$PMC")
  # With PMC there is nothing left for root to provide: the counters are already
  # readable, exactly, from EL0. Only the kperf fallback needs the prompt.
  if [[ "$PMC" == 1 || "${NO_SUDO:-0}" == 1 || "$(id -u)" -eq 0 ]]; then
    [[ "${NO_SUDO:-0}" == 1 && "$PMC" != 1 ]] && \
      warn "NO_SUDO=1 without PMC: no cycle counters; ratios still valid"
    env "${env_args[@]}" bash "$REPO_ROOT/utils/taint_libsodium_sudo_run.sh" \
      || die "run failed"
  else
    info "    sudo needed for kperf cycle counters -- you will be prompted"
    sudo -E env "${env_args[@]}" bash "$REPO_ROOT/utils/taint_libsodium_sudo_run.sh" \
      || die "run failed"
    # sudo wrote them; hand them back so the report and any later run can read.
    [[ -n "${SUDO_USER:-$USER}" ]] && sudo chown -R "${SUDO_USER:-$USER}" "$OUT" 2>/dev/null
  fi
fi

# ---------------------------------------------------------------- report
if want report; then
  [[ -f "$OUT/cio.csv" ]] || die "no results at $OUT"
  OUT="$OUT" python3 "$REPO_ROOT/utils/taint_libsodium_sudo_report.py"
  cat <<EOF

$(printf '\033[1m')Results: $OUT$(printf '\033[0m')
  cio.csv          one row per benchmark/arm/rep
  provenance.txt   toolchain, flags, cntfrq, and the driver -O level

To compare against gem5, the same arms are in
paper_experiments/09-libsodium-cio-parity/data/gem5_api_bracket.csv
(cfg=serdit is the serialising MSR DIT, which is what this silicon does).
Read blanket first: if it is free, every selective policy is spending
switches to recover nothing, which is what experiment 09 exists to show.
EOF
fi

info "done: $STAGES"
