#!/usr/bin/env python3
"""Experiment 14: the paper chart as a LaTeX table, in the style of the MTE paper's overhead tables
(UT-Security/mte-paper, overview.tex): gray booktabs rules, tinted header cells, every cell a
ratio to the unhardened build coloured by a white-to-dark-red gradient above 1.00 and green below,
a bold geometric-mean row. Reads the analysis summary and writes three files:

  awslc_gradient.tex     the colour scale and the \\gradient / \\gradientbold macros (preamble; once per document)
  awslc_paper_rows.tex   the table: the paper's ten rows x five arms, ratios to A, geomean over every cell
  awslc_m4.tex  the same format over every BRACKETED row, in bands: five groups of 20% from the slowest to
                         the fastest, then the geomean of all of them. Ratios are to the Coarse arm by default
                         (--baseline A for unhardened), so they isolate the mode switches; rows are ranked once by
                         the AWS default column (--rank-by none ranks each column by itself); --bands 25,50,25 or
                         any list of percentages changes the cut; --band-arms adds or drops columns
  awslc_standalone.tex   a one-page document that inputs all of them, to compile a preview (tectonic / pdflatex)

Usage:  latex_table_awslc.py summary.json --out DIR [--scale-max 5] [--bands 20,20,20,20,20] [--rank-by B|none] [--baseline C|A] [--band-arms B,Bs,H,Hs]
                              [--census data/dit_census.json]   (default: <out>/../../data/dit_census.json when it exists)

With a census the band table covers only the rows that enter the DIT bracket (a row that never enters it
runs the same instructions in every arm and can only dilute the bands); the caption says how many were left
out and why. The ten-row table is unaffected: its rows all enter the bracket.

The rows and arm names are the plot script's (plot_awslc.py), so the table and paper_rows.png always
agree. A suspect cell (median known wrong) is printed with a dagger and left uncoloured; nothing is left
out. Values are the ratio of cycles per operation to arm A, two decimals, as in the MTE tables (no x).
"""
import json, os, sys, argparse, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from plot_awslc import ARMS, PAPER, COLOR, geomean   # one source of truth for rows, arms, palette

# header text per arm: the user's terminology, as a two-level header (group / variant)
GROUP = [('C', 'Coarse', 1), ('B', 'AWS default', 2), ('H', 'AWS hoist', 2)]   # (first arm, label, columns)
VARIANT = {'C': '', 'B': '', 'Bs': '+ sb', 'H': '', 'Hs': '+ sb'}

def tex_escape(s):
    return s.replace('\\', r'\textbackslash{}').replace('&', r'\&').replace('%', r'\%').replace('_', r'\_').replace('#', r'\#')

def ratio(pct):
    return pct / 100 + 1

GRADIENT = r"""%% Colour scale and cell macros for the AWS-LC table (generated by latex_table_awslc.py; the
%% macro is the MTE paper's \gradient, UT-Security/mte-paper overview.tex).
%% Needs: \usepackage[table]{xcolor} \usepackage{etoolbox} \usepackage{pgf} (or tikz) \usepackage{booktabs}
\definecolor{awslow}{HTML}{306844}   %% dark green: faster than unhardened
\definecolor{awsmid}{HTML}{FFFFFF}   %% white: 1.00, no cost
\definecolor{awshigh}{HTML}{c30101}  %% dark red: the top of the scale
\newcommand*{\awsopacity}{90}
\newcommand*{\awsminval}{0.0}
\newcommand*{\awsmidval}{1.0}
\newcommand*{\awsmaxval}{__MAX__}
%% \awsgradient{1.83} prints 1.83 on a cell coloured by where it sits between \awsminval, \awsmidval and \awsmaxval;
%% a value outside the scale is printed uncoloured.
\newcommand{\awsgradient}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{#1}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{#1}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} #1%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} #1%%
      }%%
    }%%
  }%%
}
\newcommand{\awsgradientbold}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{\textbf{#1}}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{\textbf{#1}}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} \textbf{#1}%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} \textbf{#1}%%
      }%%
    }%%
  }%%
}
"""

def header_tint(arm):
    """A light tint of the chart's arm colour for the header cell, as an HTML hex (about 25% over white)."""
    h = COLOR[arm].lstrip('#'); r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    mix = lambda c: int(round(255 - (255 - c) * 0.28))
    return f"{mix(r):02X}{mix(g):02X}{mix(b):02X}"

GROUP_ARMS = {'C': ['C'], 'B': ['B', 'Bs'], 'H': ['H', 'Hs']}   # which arms sit under each group label

def table_open(comment, first_col='Benchmark', arms=ARMS):
    """The shared opening of both tables: table environment, sizes, the two header rows, the rule. `arms`
    selects the columns; a group header spans however many of its arms are present."""
    L = [r"%% " + comment, r"%% (generated by latex_table_awslc.py from the analysis summary; edit the generator, not this file).",
         r"%% Preamble: \input{awslc_gradient} plus the packages it names.",
         r"\begin{table}[t]", r"\centering\scriptsize",
         r"\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{l *{%d}{c}}" % len(arms), r"\arrayrulecolor{gray}"]
    top = [""]
    for arm, label, _ in GROUP:
        n = sum(1 for a in GROUP_ARMS[arm] if a in arms)
        if not n: continue
        cell = r"\cellcolor[HTML]{%s}\textbf{%s}" % (header_tint(arm), label)
        top.append(r"\multicolumn{%d}{c}{%s}" % (n, cell) if n > 1 else cell)
    L.append(' & '.join(top) + r" \\")
    L.append(' & '.join([r"\textbf{%s}" % first_col] + [r"\textbf{%s}" % VARIANT[a] if VARIANT[a] else '' for a in arms]) + r" \\")
    L.append(r"\midrule")
    return L

def table_close(caption, label):
    return [r"\bottomrule", r"\end{tabular}", r"\caption{%s}" % caption, r"\label{%s}" % label,
            r"\setlength{\aboverulesep}{0.6ex}\setlength{\belowrulesep}{0.9ex}", r"\end{table}"]

def bands_table(an, scale_max, bands=(20, 20, 20, 20, 20), rank_by='B', arms=('B', 'Bs', 'H', 'Hs'), census=None, baseline='C'):
    """All bracketed rows, grouped. One row per band, from the slowest to the fastest, then the geomean over every
    row. Every cell is the geometric mean of cycles-per-op ratios to `baseline`: with baseline C (Coarse, DIT on for
    the whole process) the ratio isolates what the mode switches cost, since both arms run every instruction under
    DIT and only the bracket's msr/mrs (and sb) differ; with baseline A it is the total cost over unhardened. The rows
    are ranked once, by the `rank_by` arm's ratio (default: AWS default), so a band holds the same benchmarks in every
    column; rank_by=None ranks each column by itself. Rows the census says never enter the bracket are left out.
    Every kept row counts; a band that contains a suspect cell is marked with a dagger."""
    need = set(arms) | {baseline} | ({rank_by} if rank_by else set())
    rows = [r for r in an['rows'].values() if all(x in r['cycles'] for x in need)]
    left_out = 0
    if census:
        epc = {x.get('key', x['description']): x['entries_per_call'] for x in census['rows']}
        kept = [r for r in rows if epc.get(r['key'], 1) > 0]
        left_out = len(rows) - len(kept); rows = kept
    n = len(rows)
    def rat(r, a): return r['cycles'][a] / r['cycles'][baseline]
    def sus(r, a): return a in r.get('suspect', []) or baseline in r.get('suspect', [])
    def gm(vals): return math.exp(sum(math.log(v) for v in vals) / len(vals)) if vals else float('nan')
    # band boundaries from cumulative percentages, largest ratio first
    cuts, acc = [0], 0.0
    for b in bands: acc += b; cuts.append(int(round(n * acc / 100)))
    cuts[-1] = n
    def band_label(i):
        lo, hi = sum(bands[:i]), sum(bands[:i + 1]); k = cuts[i + 1] - cuts[i]
        if i == 0: return r"Slowest %g\%% (%d)" % (bands[0], k)
        if i == len(bands) - 1: return r"Fastest %g\%% (%d)" % (bands[-1], k)
        return r"%g--%g\%% (%d)" % (lo, hi, k)
    per_arm = {}
    for a in arms:
        order = sorted(rows, key=lambda r: -rat(r, rank_by or a))          # slowest first
        vals = [rat(r, a) for r in order]; flags = [sus(r, a) for r in order]
        cells = {}
        for i in range(len(bands)):
            sl = slice(cuts[i], cuts[i + 1]); cells[i] = (gm(vals[sl]), any(flags[sl]))
        cells['all'] = (gm(vals), any(flags))
        per_arm[a] = cells
    L = table_open("Every bracketed row of the run in bands; each cell is a geometric mean of cycles-per-op ratios to the %s arm" % ARM_LABEL_TEX.get(baseline, baseline),
                   first_col='Benchmarks', arms=arms)
    suspect_rows = sorted(r['key'] for r in rows if r.get('suspect'))
    dag = False
    order_keys = list(range(len(bands))) + ['all']
    for key in order_keys:
        bold = key == 'all'
        label = r"\textbf{All %d bracketed benchmarks}" % n if bold else band_label(key)
        if bold: L.append(r"\midrule")
        cells = []
        for a in arms:
            v, s_ = per_arm[a][key]
            mark = (key != 'all') and s_
            dag |= mark
            cells.append(r"%s{%.2f}%s" % (r"\awsgradientbold" if bold else r"\awsgradient", v, r"$^\dagger$" if mark else ''))
        L.append(label + ' & ' + ' & '.join(cells) + r" \\")
    v = an['validity']
    base_txt = (r"the Coarse arm (DIT on for the whole process), so the ratio isolates the cost of the bracket's mode switches from the cost of running under DIT"
                if baseline == 'C' else r"the unhardened build (1.00 = no cost)")
    how = (r"Rows are ranked once, by the %s column, so a band holds the same benchmarks in every column." % ARM_LABEL_TEX.get(rank_by, rank_by) if rank_by
           else r"Each column ranks its own cells, so a band holds different benchmarks in different columns.")
    which = (r"over the %d rows that enter the bracket (%d rows of the run never do and are left out; they share a selection name with rows that do, so the tool runs them anyway)" % (n, left_out)
             if census else r"over all %d rows" % n)
    bandtxt = ', '.join(r"%g\%%" % b for b in bands)
    cap = (r"\textbf{AWS-LC's bracket against coarse DIT across every bracketed \texttt{bssl speed} row.} \textit{Geometric mean of cycles per operation relative to %s, "
           r"%s, in %d bands of %s from the slowest to the fastest, and over all of them. %s "
           r"Apple M4 P-core, hard-bound, %s\,ms windows, medians of %s repetitions, %s runs combined by the per-cell median. Every kept cell counts.%s}"
           % (base_txt, which, len(bands), bandtxt, how, v.get('timeout_ms'), v.get('reps'), v.get('runs_count', 1),
              (r" The counter fault corrupted a median in %s (%s); $^\dagger$ marks the band it fell into."
               % ('one row' if len(suspect_rows) == 1 else '%d rows' % len(suspect_rows), ', '.join(tex_escape(k) for k in suspect_rows))) if suspect_rows else ''))
    L += table_close(cap, 'tab:awslc-m4')
    return '\n'.join(L) + '\n'

ARM_LABEL_TEX = {'C': 'Coarse', 'B': 'AWS default', 'Bs': 'AWS default + sb', 'H': 'AWS hoist', 'Hs': 'AWS hoist + sb'}

def table(an, scale_max):
    rows = [(lab, an['rows'].get(k)) for lab, k in PAPER]
    rows = [(lab, r) for lab, r in rows if r]
    used = [r for _, r in rows]
    L = table_open("The paper's ten rows as a table")
    for lab, r in rows:
        cells = []
        for a in ARMS:
            p = r['pct'].get(a)
            if p is None or p != p: cells.append('--'); continue
            v = ratio(p)
            if a in r.get('suspect', []):
                cells.append(f"{v:.2f}$^\\dagger$" if v < 100 else f"{v:.2g}$^\\dagger$")   # kept, uncoloured, marked
            else:
                cells.append(r"\awsgradient{%.2f}" % v)
        L.append(tex_escape(lab) + ' & ' + ' & '.join(cells) + r" \\")
    L.append(r"\midrule")
    gm = [r"\awsgradientbold{%.2f}" % ratio(geomean(used, a, True)) for a in ARMS]   # every cell counts
    L.append(r"\textbf{Geomean} & " + ' & '.join(gm) + r" \\")
    v = an['validity']
    sus = any(r.get('suspect') for r in used)
    cap = (r"\textbf{AWS-LC's DIT bracket on \texttt{bssl speed}.} \textit{Cycles per operation relative to the "
           r"unhardened build (1.00 = no cost) on an Apple M4 P-core, hard-bound, %s\,ms windows, medians of %s repetitions, "
           r"%s runs combined by the per-cell median. Coarse sets DIT once for the whole process; AWS default is the bracket as "
           r"shipped; AWS hoist is the vendor's \texttt{-dit} mode; + sb adds "
           r"the barrier after each enable. Geomean is over every cell.%s}"
           % (v.get('timeout_ms'), v.get('reps'), v.get('runs_count', 1), r" $^\dagger$ marks a cell whose median the counter fault corrupted; kept, not to be read." if sus else ''))
    L += table_close(cap, 'tab:awslc-bracket')
    return '\n'.join(L) + '\n'

STANDALONE = r"""\documentclass[10pt,twocolumn]{article}
\usepackage[letterpaper,textwidth=7in,columnsep=0.33in,textheight=9.25in]{geometry}   % USENIX: 3.33in columns
\usepackage{booktabs}
\usepackage[table]{xcolor}
\usepackage{etoolbox}
\usepackage{pgf}
\usepackage{newtxtext}   % Times clone that is embedded (the base-14 `times' is not, and a viewer then drops bold/italic)
\input{awslc_gradient}
\pagestyle{empty}
\begin{document}
\input{awslc_paper_rows}
\input{awslc_m4}
\end{document}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('json', help='summary.json written by analyze_awslc.py')
    ap.add_argument('--out', required=True, help='directory for the .tex files')
    ap.add_argument('--scale-max', type=float, default=None, help='top of the colour scale (default: the largest clean ratio rounded up)')
    ap.add_argument('--bands', default='20,20,20,20,20', help='percent of rows in each band of the all-rows table, slowest first (any number of bands)')
    ap.add_argument('--rank-by', default='B', help='rank the rows once by this arm (default B, AWS default); "none" ranks each column by itself')
    ap.add_argument('--baseline', default='C', choices=['A', 'C'], help='the ratio denominator of the all-rows table: C Coarse (default; isolates the mode switches) or A unhardened')
    ap.add_argument('--band-arms', default='B,Bs,H,Hs', help='columns of the all-rows table (default: the four AWS arms; add C for Coarse)')
    ap.add_argument('--census', default=None, help='dit_census.json; the band table then covers only rows that enter the bracket (default: <out>/../../data/dit_census.json if present; "none" to disable)')
    a = ap.parse_args()
    census = None
    cpath = a.census if a.census else os.path.join(a.out, '..', '..', 'data', 'dit_census.json')
    if cpath != 'none' and os.path.exists(cpath): census = json.load(open(cpath))
    bands = tuple(float(x) for x in a.bands.split(','))
    band_arms = tuple(x for x in ARMS if x in a.band_arms.split(','))
    an = json.load(open(a.json))
    os.makedirs(a.out, exist_ok=True)
    clean = [ratio(r['pct'][x]) for _, k in PAPER if k in an['rows'] for r in [an['rows'][k]] for x in ARMS
             if x in r['pct'] and r['pct'][x] == r['pct'][x] and x not in r.get('suspect', [])]
    scale_max = a.scale_max or (math.ceil(max(clean)) if clean else 5)
    open(os.path.join(a.out, 'awslc_gradient.tex'), 'w').write(GRADIENT.replace('%%', '%').replace('__MAX__', f"{scale_max:g}"))
    open(os.path.join(a.out, 'awslc_paper_rows.tex'), 'w').write(table(an, scale_max))
    rank_by = None if a.rank_by in ('none', '') else a.rank_by
    open(os.path.join(a.out, 'awslc_m4.tex'), 'w').write(bands_table(an, scale_max, bands, rank_by, band_arms, census, a.baseline))
    open(os.path.join(a.out, 'awslc_standalone.tex'), 'w').write(STANDALONE)
    print(f"wrote {a.out}/awslc_gradient.tex, awslc_paper_rows.tex, awslc_m4.tex (bands {a.bands}, columns {','.join(band_arms)}, "
          f"{'ranked by ' + rank_by if rank_by else 'each column ranked on its own cells'}, baseline {a.baseline}{', bracketed rows only per ' + cpath if census else ''}), awslc_standalone.tex (colour scale 0..{scale_max:g}, white at 1.00)")

if __name__ == '__main__':
    main()
