#!/usr/bin/env python3
"""Experiment 14: the paper chart as a LaTeX table, in the style of the MTE paper's overhead tables
(UT-Security/mte-paper, overview.tex): gray booktabs rules, tinted header cells, every cell a
ratio to the unhardened build coloured by a white-to-dark-red gradient above 1.00 and green below,
a bold geometric-mean row. Reads the analysis summary and writes three files:

  awslc_gradient.tex     the colour scale and the \\gradient / \\gradientbold macros (preamble; once per document)
  awslc_paper_rows.tex   the table: the paper's ten rows x five arms, ratios to A, geomean over every cell
  awslc_all_rows_bands.tex  the same format over ALL rows, grouped: the geomean of every row, then the slowest
                         25%, the middle 50% and the fastest 25% of each arm's cells (each column ranks its own
                         cells; --rank-by B ranks every column by the AWS default column instead). The AWS
                         columns only by default; --band-arms C,B,Bs,H,Hs puts Coarse back
  awslc_standalone.tex   a one-page document that inputs all of them, to compile a preview (tectonic / pdflatex)

Usage:  latex_table_awslc.py summary.json --out DIR [--scale-max 5] [--bands 25,50,25] [--rank-by B] [--band-arms B,Bs,H,Hs]
                              [--census data/dit_census.json]   (default: <out>/../../data/dit_census.json when it exists)

With a census the band table covers only the rows that enter the DIT bracket (a row that never enters it
runs the same instructions in every arm and can only dilute the bands); the caption says how many were left
out and why. The ten-row table is unaffected: its rows all enter the bracket.

The rows and arm names are the plot script's (plot_awslc.py), so the table and paper_rows.png always
agree. A suspect cell (median known wrong) is printed with a dagger and left uncoloured; nothing is left
out. Values are the ratio of cycles per operation to arm A, two decimals, as in the MTE tables (no x).
"""
import json, os, sys, argparse, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from plot_awslc import ARMS, PAPER, COLOR, geomean   # one source of truth for rows, arms, palette

# header text per arm: the user's terminology, as a two-level header (group / variant)
GROUP = [('C', 'Coarse', 1), ('B', 'AWS default', 2), ('H', 'AWS hoist', 2)]   # (first arm, label, columns)
VARIANT = {'C': '', 'B': '', 'Bs': '+ sb', 'H': '', 'Hs': '+ sb'}

def tex_escape(s):
    return s.replace('\\', r'\textbackslash{}').replace('&', r'\&').replace('%', r'\%').replace('_', r'\_').replace('#', r'\#')

def ratio(pct):
    return pct / 100 + 1

GRADIENT = r"""%% Colour scale and cell macros for the AWS-LC table (generated by latex_table_awslc.py; the
%% macro is the MTE paper's \gradient, UT-Security/mte-paper overview.tex).
%% Needs: \usepackage[table]{xcolor} \usepackage{etoolbox} \usepackage{pgf} (or tikz) \usepackage{booktabs}
\definecolor{awslow}{HTML}{306844}   %% dark green: faster than unhardened
\definecolor{awsmid}{HTML}{FFFFFF}   %% white: 1.00, no cost
\definecolor{awshigh}{HTML}{c30101}  %% dark red: the top of the scale
\newcommand*{\awsopacity}{90}
\newcommand*{\awsminval}{0.0}
\newcommand*{\awsmidval}{1.0}
\newcommand*{\awsmaxval}{__MAX__}
%% \awsgradient{1.83} prints 1.83 on a cell coloured by where it sits between \awsminval, \awsmidval and \awsmaxval;
%% a value outside the scale is printed uncoloured.
\newcommand{\awsgradient}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{#1}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{#1}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} #1%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} #1%%
      }%%
    }%%
  }%%
}
\newcommand{\awsgradientbold}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{\textbf{#1}}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{\textbf{#1}}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} \textbf{#1}%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} \textbf{#1}%%
      }%%
    }%%
  }%%
}
"""

def header_tint(arm):
    """A light tint of the chart's arm colour for the header cell, as an HTML hex (about 25% over white)."""
    h = COLOR[arm].lstrip('#'); r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    mix = lambda c: int(round(255 - (255 - c) * 0.28))
    return f"{mix(r):02X}{mix(g):02X}{mix(b):02X}"

GROUP_ARMS = {'C': ['C'], 'B': ['B', 'Bs'], 'H': ['H', 'Hs']}   # which arms sit under each group label

def table_open(comment, first_col='Benchmark', arms=ARMS):
    """The shared opening of both tables: table environment, sizes, the two header rows, the rule. `arms`
    selects the columns; a group header spans however many of its arms are present."""
    L = [r"%% " + comment, r"%% (generated by latex_table_awslc.py from the analysis summary; edit the generator, not this file).",
         r"%% Preamble: \input{awslc_gradient} plus the packages it names.",
         r"\begin{table}[t]", r"\centering\scriptsize",
         r"\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}\setlength{\tabcolsep}{3pt}",
         r"\begin{tabular}{l *{%d}{c}}" % len(arms), r"\arrayrulecolor{gray}"]
    top = [""]
    for arm, label, _ in GROUP:
        n = sum(1 for a in GROUP_ARMS[arm] if a in arms)
        if not n: continue
        cell = r"\cellcolor[HTML]{%s}\textbf{%s}" % (header_tint(arm), label)
        top.append(r"\multicolumn{%d}{c}{%s}" % (n, cell) if n > 1 else cell)
    L.append(' & '.join(top) + r" \\")
    L.append(' & '.join([r"\textbf{%s}" % first_col] + [r"\textbf{%s}" % VARIANT[a] if VARIANT[a] else '' for a in arms]) + r" \\")
    L.append(r"\midrule")
    return L

def table_close(caption, label):
    return [r"\bottomrule", r"\end{tabular}", r"\caption{%s}" % caption, r"\label{%s}" % label,
            r"\setlength{\aboverulesep}{0.6ex}\setlength{\belowrulesep}{0.9ex}", r"\end{table}"]

def bands_table(an, scale_max, bands=(25, 50, 25), rank_by=None, arms=('B', 'Bs', 'H', 'Hs'), census=None):
    """All rows, grouped. One row per band: the geomean over every row, then the slowest `bands[0]`%, the
    middle `bands[1]`% (centred on the median) and the fastest `bands[2]`% of the cells. Each column ranks its
    own cells unless rank_by names an arm, in which case every column follows that arm's order. Every cell
    counts; a band that contains a suspect cell is marked with a dagger."""
    rows = [r for r in an['rows'].values() if all(x in r['pct'] and r['pct'][x] == r['pct'][x] for x in arms)]
    left_out = 0
    if census:   # keep only the rows the census saw entering the bracket at least once per call
        epc = {x.get('key', x['description']): x['entries_per_call'] for x in census['rows']}   # key = description + size, the driver's row key
        kept = [r for r in rows if epc.get(r['key'], 1) > 0]
        left_out = len(rows) - len(kept); rows = kept
    n = len(rows)
    def gm(vals): return math.exp(sum(math.log(v) for v in vals) / len(vals)) if vals else float('nan')
    def band_slices(n):
        k_slow, k_mid, k_fast = (int(round(n * b / 100)) for b in bands)
        lo = (n - k_mid) // 2
        return {'slow': slice(0, k_slow), 'mid': slice(lo, lo + k_mid), 'fast': slice(n - k_fast, n)}, (k_slow, k_mid, k_fast)
    sl, (k_slow, k_mid, k_fast) = band_slices(n)
    per_arm = {}
    for a in arms:
        key = rank_by or a
        order = sorted(rows, key=lambda r: -ratio(r['pct'][key]))          # slowest first
        vals = [ratio(r['pct'][a]) for r in order]
        sus = [a in r.get('suspect', []) or 'A' in r.get('suspect', []) for r in order]
        per_arm[a] = {'all': (gm(vals), any(sus)), 'slow': (gm(vals[sl['slow']]), any(sus[sl['slow']])),
                      'mid': (gm(vals[sl['mid']]), any(sus[sl['mid']])), 'fast': (gm(vals[sl['fast']]), any(sus[sl['fast']]))}
    labels = [('all', r"\textbf{All %d benchmarks}" % n if not census else r"\textbf{All %d bracketed benchmarks}" % n, True), ('slow', r"Slowest %g\%% (%d)" % (bands[0], k_slow), False),
              ('mid', r"Middle %g\%% (%d)" % (bands[1], k_mid), False), ('fast', r"Fastest %g\%% (%d)" % (bands[2], k_fast), False)]
    L = table_open("Every row of the run, grouped into bands of each arm's cells; each cell is a geometric mean of ratios to the unhardened build", first_col='Benchmarks', arms=arms)
    suspect_rows = sorted(r['key'] for r in rows if r.get('suspect'))
    dag = False
    for key, label, bold in labels:
        cells = []
        for a in arms:
            v, s_ = per_arm[a][key]
            mark = key != 'all' and s_          # the All row holds every row by construction; the caption names the suspect ones
            dag |= mark
            mac = r"\awsgradientbold" if bold else r"\awsgradient"
            cells.append(r"%s{%.2f}%s" % (mac, v, r"$^\dagger$" if mark else ''))
        L.append(label + ' & ' + ' & '.join(cells) + r" \\")
        if key == 'all': L.append(r"\midrule")
    v = an['validity']
    how = (r"Each column ranks its own cells, so a band holds different benchmarks in different columns." if not rank_by
           else r"Every column follows the %s column's ranking, so a band holds the same benchmarks across the row." % ARM_LABEL_TEX.get(rank_by, rank_by))
    which = (r"over all %d rows" % n if not census else
             r"over the %d rows that enter the bracket (%d rows of the run never do: hashes, HMACs, signature verification; "
             r"they run the same instructions in every arm and are left out)" % (n, left_out))
    cap = (r"\textbf{AWS-LC's DIT bracket across every \texttt{bssl speed} row.} \textit{Geometric mean of cycles per operation relative to the "
           r"unhardened build (1.00 = no cost) %s, and over the slowest %g\%%, the middle %g\%% and the fastest %g\%% of them. %s "
           r"Apple M4 P-core, hard-bound, %s\,ms windows, medians of %s repetitions, %s runs combined by the per-cell median. Every cell counts.%s}"
           % (which, bands[0], bands[1], bands[2], how, v.get('timeout_ms'), v.get('reps'), v.get('runs_count', 1),
              (r" The counter fault corrupted a median in %s (%s); that row is in every All cell, and $^\dagger$ marks the band it fell into."
               % ('one row' if len(suspect_rows) == 1 else '%d rows' % len(suspect_rows), ', '.join(tex_escape(k) for k in suspect_rows))) if suspect_rows else ''))
    L += table_close(cap, 'tab:awslc-bands')
    return '\n'.join(L) + '\n'

ARM_LABEL_TEX = {'C': 'Coarse', 'B': 'AWS default', 'Bs': 'AWS default + sb', 'H': 'AWS hoist', 'Hs': 'AWS hoist + sb'}

def table(an, scale_max):
    rows = [(lab, an['rows'].get(k)) for lab, k in PAPER]
    rows = [(lab, r) for lab, r in rows if r]
    used = [r for _, r in rows]
    L = table_open("The paper's ten rows as a table")
    for lab, r in rows:
        cells = []
        for a in ARMS:
            p = r['pct'].get(a)
            if p is None or p != p: cells.append('--'); continue
            v = ratio(p)
            if a in r.get('suspect', []):
                cells.append(f"{v:.2f}$^\\dagger$" if v < 100 else f"{v:.2g}$^\\dagger$")   # kept, uncoloured, marked
            else:
                cells.append(r"\awsgradient{%.2f}" % v)
        L.append(tex_escape(lab) + ' & ' + ' & '.join(cells) + r" \\")
    L.append(r"\midrule")
    gm = [r"\awsgradientbold{%.2f}" % ratio(geomean(used, a, True)) for a in ARMS]   # every cell counts
    L.append(r"\textbf{Geomean} & " + ' & '.join(gm) + r" \\")
    v = an['validity']
    sus = any(r.get('suspect') for r in used)
    cap = (r"\textbf{AWS-LC's DIT bracket on \texttt{bssl speed}.} \textit{Cycles per operation relative to the "
           r"unhardened build (1.00 = no cost) on an Apple M4 P-core, hard-bound, %s\,ms windows, medians of %s repetitions, "
           r"%s runs combined by the per-cell median. Coarse sets DIT once for the whole process; AWS default is the bracket as "
           r"shipped; AWS hoist is the vendor's \texttt{-dit} mode; + sb adds "
           r"the barrier after each enable. Geomean is over every cell.%s}"
           % (v.get('timeout_ms'), v.get('reps'), v.get('runs_count', 1), r" $^\dagger$ marks a cell whose median the counter fault corrupted; kept, not to be read." if sus else ''))
    L += table_close(cap, 'tab:awslc-bracket')
    return '\n'.join(L) + '\n'

STANDALONE = r"""\documentclass[10pt,twocolumn]{article}
\usepackage[letterpaper,textwidth=7in,columnsep=0.33in,textheight=9.25in]{geometry}   % USENIX: 3.33in columns
\usepackage{booktabs}
\usepackage[table]{xcolor}
\usepackage{etoolbox}
\usepackage{pgf}
\usepackage{newtxtext}   % Times clone that is embedded (the base-14 `times' is not, and a viewer then drops bold/italic)
\input{awslc_gradient}
\pagestyle{empty}
\begin{document}
\input{awslc_paper_rows}
\input{awslc_all_rows_bands}
\end{document}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('json', help='summary.json written by analyze_awslc.py')
    ap.add_argument('--out', required=True, help='directory for the .tex files')
    ap.add_argument('--scale-max', type=float, default=None, help='top of the colour scale (default: the largest clean ratio rounded up)')
    ap.add_argument('--bands', default='25,50,25', help='percent of rows in the slowest, middle and fastest band of the all-rows table')
    ap.add_argument('--rank-by', default=None, choices=ARMS, help='rank every column of the all-rows table by this arm (default: each column by itself)')
    ap.add_argument('--band-arms', default='B,Bs,H,Hs', help='columns of the all-rows table (default: the four AWS arms; add C for Coarse)')
    ap.add_argument('--census', default=None, help='dit_census.json; the band table then covers only rows that enter the bracket (default: <out>/../../data/dit_census.json if present; "none" to disable)')
    a = ap.parse_args()
    census = None
    cpath = a.census if a.census else os.path.join(a.out, '..', '..', 'data', 'dit_census.json')
    if cpath != 'none' and os.path.exists(cpath): census = json.load(open(cpath))
    bands = tuple(float(x) for x in a.bands.split(','))
    band_arms = tuple(x for x in ARMS if x in a.band_arms.split(','))
    an = json.load(open(a.json))
    os.makedirs(a.out, exist_ok=True)
    clean = [ratio(r['pct'][x]) for _, k in PAPER if k in an['rows'] for r in [an['rows'][k]] for x in ARMS
             if x in r['pct'] and r['pct'][x] == r['pct'][x] and x not in r.get('suspect', [])]
    scale_max = a.scale_max or (math.ceil(max(clean)) if clean else 5)
    open(os.path.join(a.out, 'awslc_gradient.tex'), 'w').write(GRADIENT.replace('%%', '%').replace('__MAX__', f"{scale_max:g}"))
    open(os.path.join(a.out, 'awslc_paper_rows.tex'), 'w').write(table(an, scale_max))
    open(os.path.join(a.out, 'awslc_all_rows_bands.tex'), 'w').write(bands_table(an, scale_max, bands, a.rank_by, band_arms, census))
    open(os.path.join(a.out, 'awslc_standalone.tex'), 'w').write(STANDALONE)
    print(f"wrote {a.out}/awslc_gradient.tex, awslc_paper_rows.tex, awslc_all_rows_bands.tex (bands {a.bands}, columns {','.join(band_arms)}, "
          f"{'ranked by ' + a.rank_by if a.rank_by else 'each column ranked on its own cells'}{', bracketed rows only per ' + cpath if census else ''}), awslc_standalone.tex (colour scale 0..{scale_max:g}, white at 1.00)")

if __name__ == '__main__':
    main()
