#!/usr/bin/env python3
"""Experiment 14: the paper chart as a LaTeX table, in the style of the MTE paper's overhead tables
(UT-Security/mte-paper, overview.tex): gray booktabs rules, tinted header cells, every cell a
ratio to the unhardened build coloured by a white-to-dark-red gradient above 1.00 and green below,
a bold geometric-mean row. Reads the analysis summary and writes three files:

  awslc_gradient.tex     the colour scale and the \\gradient / \\gradientbold macros (preamble; once per document)
  awslc_paper_rows.tex   the table: the paper's ten rows x five arms, ratios to A, geomean over every cell
  awslc_standalone.tex   a one-page document that inputs both, to compile a preview (tectonic / pdflatex)

Usage:  latex_table_awslc.py summary.json --out DIR [--scale-max 5]

The rows and arm names are the plot script's (plot_awslc.py), so the table and paper_rows.png always
agree. A suspect cell (median known wrong) is printed with a dagger and left uncoloured; nothing is left
out. Values are the ratio of cycles per operation to arm A, two decimals, as in the MTE tables (no x).
"""
import json, os, sys, argparse, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from plot_awslc import ARMS, PAPER, COLOR, geomean   # one source of truth for rows, arms, palette

# header text per arm: the user's terminology, as a two-level header (group / variant)
GROUP = [('C', 'Coarse', 1), ('B', 'AWS default', 2), ('H', 'AWS hoist', 2)]   # (first arm, label, columns)
VARIANT = {'C': '', 'B': '', 'Bs': '+ sb', 'H': '', 'Hs': '+ sb'}

def tex_escape(s):
    return s.replace('\\', r'\textbackslash{}').replace('&', r'\&').replace('%', r'\%').replace('_', r'\_').replace('#', r'\#')

def ratio(pct):
    return pct / 100 + 1

GRADIENT = r"""%% Colour scale and cell macros for the AWS-LC table (generated by latex_table_awslc.py; the
%% macro is the MTE paper's \gradient, UT-Security/mte-paper overview.tex).
%% Needs: \usepackage[table]{xcolor} \usepackage{etoolbox} \usepackage{pgf} (or tikz) \usepackage{booktabs}
\definecolor{awslow}{HTML}{306844}   %% dark green: faster than unhardened
\definecolor{awsmid}{HTML}{FFFFFF}   %% white: 1.00, no cost
\definecolor{awshigh}{HTML}{c30101}  %% dark red: the top of the scale
\newcommand*{\awsopacity}{90}
\newcommand*{\awsminval}{0.0}
\newcommand*{\awsmidval}{1.0}
\newcommand*{\awsmaxval}{__MAX__}
%% \awsgradient{1.83} prints 1.83 on a cell coloured by where it sits between \awsminval, \awsmidval and \awsmaxval;
%% a value outside the scale is printed uncoloured.
\newcommand{\awsgradient}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{#1}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{#1}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} #1%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} #1%%
      }%%
    }%%
  }%%
}
\newcommand{\awsgradientbold}[1]{%%
  \ifdimcomp{#1pt}{>}{\awsmaxval pt}{\textbf{#1}}{%%
    \ifdimcomp{#1pt}{<}{\awsminval pt}{\textbf{#1}}{%%
      \ifdimcomp{#1pt}{<}{\awsmidval pt}{%%
        \pgfmathparse{int(round(100*(#1-\awsminval)/(\awsmidval-\awsminval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awsmid!\awstempa!awslow!\awsopacity} \textbf{#1}%%
      }{%%
        \pgfmathparse{int(round(100*(#1-\awsmidval)/(\awsmaxval-\awsmidval)))}\xdef\awstempa{\pgfmathresult}%%
        \cellcolor{awshigh!\awstempa!awsmid!\awsopacity} \textbf{#1}%%
      }%%
    }%%
  }%%
}
"""

def header_tint(arm):
    """A light tint of the chart's arm colour for the header cell, as an HTML hex (about 25% over white)."""
    h = COLOR[arm].lstrip('#'); r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    mix = lambda c: int(round(255 - (255 - c) * 0.28))
    return f"{mix(r):02X}{mix(g):02X}{mix(b):02X}"

def table(an, scale_max):
    rows = [(lab, an['rows'].get(k)) for lab, k in PAPER]
    rows = [(lab, r) for lab, r in rows if r]
    used = [r for _, r in rows]
    L = []
    L.append(r"%% The paper's ten rows as a table (generated by latex_table_awslc.py from the analysis summary;")
    L.append(r"%% edit the generator, not this file). Preamble: \input{awslc_gradient} plus the packages it names.")
    L.append(r"\begin{table}[t]")
    L.append(r"\centering\scriptsize")
    L.append(r"\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}\setlength{\tabcolsep}{3pt}")
    L.append(r"\begin{tabular}{l *{%d}{c}}" % len(ARMS))
    L.append(r"\arrayrulecolor{gray}")
    # top header: group labels on tinted cells
    top = [""]
    for arm, label, n in GROUP:
        cell = r"\cellcolor[HTML]{%s}\textbf{%s}" % (header_tint(arm), label)
        top.append(r"\multicolumn{%d}{c}{%s}" % (n, cell) if n > 1 else cell)
    L.append(' & '.join(top) + r" \\")
    # second header: the variant under each group
    L.append(' & '.join([r"\textbf{Benchmark}"] + [r"\textbf{%s}" % VARIANT[a] if VARIANT[a] else '' for a in ARMS]) + r" \\")
    L.append(r"\midrule")
    for lab, r in rows:
        cells = []
        for a in ARMS:
            p = r['pct'].get(a)
            if p is None or p != p: cells.append('--'); continue
            v = ratio(p)
            if a in r.get('suspect', []):
                cells.append(f"{v:.2f}$^\\dagger$" if v < 100 else f"{v:.2g}$^\\dagger$")   # kept, uncoloured, marked
            else:
                cells.append(r"\awsgradient{%.2f}" % v)
        L.append(tex_escape(lab) + ' & ' + ' & '.join(cells) + r" \\")
    L.append(r"\midrule")
    gm = [r"\awsgradientbold{%.2f}" % ratio(geomean(used, a, True)) for a in ARMS]   # every cell counts
    L.append(r"\textbf{Geomean} & " + ' & '.join(gm) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    v = an['validity']
    sus = any(r.get('suspect') for r in used)
    L.append(r"\caption{\textbf{AWS-LC's DIT bracket on \texttt{bssl speed}.} \textit{Cycles per operation relative to the "
             r"unhardened build (1.00 = no cost) on an Apple M4 P-core, hard-bound, %s\,ms windows, medians of %s repetitions, "
             r"%s runs combined by the per-cell median. Coarse sets DIT once for the whole process; AWS default is the bracket as "
             r"shipped; AWS hoist is the vendor's \texttt{-dit} mode; + sb adds "
             r"the barrier after each enable. Geomean is over every cell.%s}}"
             % (v.get('timeout_ms'), v.get('reps'), v.get('runs_count', 1), r" $^\dagger$ marks a cell whose median the counter fault corrupted; kept, not to be read." if sus else ''))
    L.append(r"\label{tab:awslc-bracket}")
    L.append(r"\setlength{\aboverulesep}{0.6ex}\setlength{\belowrulesep}{0.9ex}")
    L.append(r"\end{table}")
    return '\n'.join(L) + '\n'

STANDALONE = r"""\documentclass[10pt,twocolumn]{article}
\usepackage[letterpaper,textwidth=7in,columnsep=0.33in,textheight=9.25in]{geometry}   % USENIX: 3.33in columns
\usepackage{booktabs}
\usepackage[table]{xcolor}
\usepackage{etoolbox}
\usepackage{pgf}
\usepackage{newtxtext}   % Times clone that is embedded (the base-14 `times' is not, and a viewer then drops bold/italic)
\input{awslc_gradient}
\pagestyle{empty}
\begin{document}
\input{awslc_paper_rows}
\end{document}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('json', help='summary.json written by analyze_awslc.py')
    ap.add_argument('--out', required=True, help='directory for the .tex files')
    ap.add_argument('--scale-max', type=float, default=None, help='top of the colour scale (default: the largest clean ratio rounded up)')
    a = ap.parse_args()
    an = json.load(open(a.json))
    os.makedirs(a.out, exist_ok=True)
    clean = [ratio(r['pct'][x]) for _, k in PAPER if k in an['rows'] for r in [an['rows'][k]] for x in ARMS
             if x in r['pct'] and r['pct'][x] == r['pct'][x] and x not in r.get('suspect', [])]
    scale_max = a.scale_max or (math.ceil(max(clean)) if clean else 5)
    open(os.path.join(a.out, 'awslc_gradient.tex'), 'w').write(GRADIENT.replace('%%', '%').replace('__MAX__', f"{scale_max:g}"))
    open(os.path.join(a.out, 'awslc_paper_rows.tex'), 'w').write(table(an, scale_max))
    open(os.path.join(a.out, 'awslc_standalone.tex'), 'w').write(STANDALONE)
    print(f"wrote {a.out}/awslc_gradient.tex, awslc_paper_rows.tex, awslc_standalone.tex (colour scale 0..{scale_max:g}, white at 1.00)")

if __name__ == '__main__':
    main()
